### ISSUE TITLE
how do i install?

### ISSUE THREAD

**Issue by cr1ptik** [kuba2k2/spicetify-beat-saber#1]
all the normal extensions are js files

**Comment by kuba2k2** [comment]
This is not an extension, but a custom app. It's designed for older Spotify clients (1.1.56, with the classic UI) so it won't work with latest versions.

If you still want to install it, get spicetify-legacy from my repository (find it on my profile), install it like you usually would. Then grab the .spa file from releases in this repo. Put the file in .spicetify/CustomApps and add the filename to the config, so that spicetify installs the app. 

It won't work with normal spicetify v1.2.1, you have to use the version from my fork.

**Comment by cr1ptik** [comment]
thanks

**Comment by kuba2k2** [comment]
FYI, if you still need it, this has been updated and works with latest versions of Spotify and Spicetify.
