### ISSUE TITLE
Update backend error

### ISSUE THREAD

**Issue by LtLasagna** [kuba2k2/spicetify-beat-saber#14]
It is fully up to date but throws this error:

![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/93097985/3281d930-ae7e-4e7a-9aef-abd9e52afa89)

I also cannot select any directories, but it is not infinitely loading like the other issue.

![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/93097985/acbe7e9b-d103-4b7d-841c-ad75a07bca8c)

**Comment by kuba2k2** [comment]
Did you install the backend and reboot your PC? Can you check what version is installed in Windows settings? Can you try fully uninstalling backend and installing it again?

**Comment by LtLasagna** [comment]
So, yes I installed the most recent version for the first time, restarted my PC. Didn't work, I tried using the previous release of both, same thing. I'm thinking maybe it's my Spotify version? Also, I can view the localhost page in my browser, but Spotify can't connect to it.

**Comment by kuba2k2** [comment]
Which localhost page? Please attach screenshots so that I know what you mean.
Please also post a screenshot of the "Programs" panel in Windows settings, so that I can see which version is installed.
The error you're getting means specifically that it **can** connect to the backend extension, and that it **is** an old version. Otherwise, a different error would show up (such as "can't connect to backend").

**Comment by LtLasagna** [comment]
Here is the programs panel
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/93097985/672ffcce-ab01-4df1-a8ac-e0bfa09f0b96)

The local host page in my browser:
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/93097985/bf51b044-3509-4dcd-b16a-6847e40ff697)

And in Spotify:
![image](https://github.com/kuba2k2/spicetify-beat-saber/assets/93097985/de16fb2f-0736-40c9-9bb0-b534a389c627)

**Comment by v1per-xd** [comment]
getting the same error

**Comment by TheRedNet** [comment]
![grafik](https://github.com/kuba2k2/spicetify-beat-saber/assets/45996791/a32904d4-d0d4-4b19-95d6-bc1a0bbc0f4e)
![grafik](https://github.com/kuba2k2/spicetify-beat-saber/assets/45996791/dd8f9317-8ebb-4421-9c40-55c6606bb1f2)
same error
for some reason you cant call localhost
because you call over https://cors-proxy.spicetify.app

**Comment by kuba2k2** [comment]
That is so awfully stupid. I did not ask to use this proxy, it must have added itself automatically. I doubt there is any way to bypass it easily.
They should have at least thought to skip the proxy when calling localhost URLs...

**Comment by kuba2k2** [comment]
Fixed thanks to @rxri. Version v2.2.0 is building right now and should be ready in a moment.
